/// <summary> This file was generated by the Objective Systems ASN1C Compiler
/// (http://www.obj-sys.com).  Version: 6.0B, Date: 28-Oct-2006.
/// </summary>
using System;
using Com.Objsys.Asn1.Runtime;
namespace Sample_xml.CAP
{
   
   public class Writer
   {
      
      [STAThread]
      public static void  Main(System.String[] args)
      {
         
         System.String filename = new System.Text.StringBuilder("message.xml").ToString();
         bool trace = true;
         
         if (args.Length > 0)
         {
            for (int i = 0; i < args.Length; i++)
            {
               if (args[i].Equals("-v"))
                  Diag.Instance().SetEnabled(true);
               else if (args[i].Equals("-o"))
                  filename = new System.Text.StringBuilder(args[++i]).ToString();
               else if (args[i].Equals("-notrace"))
                  trace = false;
               else
               {
                  System.Console.Out.WriteLine("usage: Writer [-v] [-o <filename>] [-notrace]");
                  System.Console.Out.WriteLine("   -v  verbose mode: print trace info");
                  System.Console.Out.WriteLine("   -o <filename>  " + "write encoded msg to <filename>");
                  System.Console.Out.WriteLine("   -notrace  do not display trace info");
                  System.Environment.Exit(1);
               }
            }
         }
         
         // Create a message buffer object
         Asn1XmlEncodeBuffer encodeBuffer = new Asn1XmlEncodeBuffer();
         try
         {
            Alert alert;
            alert = new Alert();
            alert.identifier = new Asn1UTF8String("43b080713727");
            alert.sender = new Asn1UTF8String("hsas@dhs.gov");
            alert.sent = new Asn1VisibleString("2003-04-02T14:39:01-05:00");
            alert.status = new Alert_status(Alert_status.actual);
            alert.msgType = new Alert_msgType(Alert_msgType.alert);
            alert.scope = new Alert_scope(Alert_scope.public_);
            
            alert.info_list = new Alert_info[1];
            alert.info_list[0] = new Alert_info();
            alert.info_list[0].category_list = new Alert_info_category[1];
            alert.info_list[0].category_list[0] = new Alert_info_category(Alert_info_category.security);
            
            alert.info_list[0].event_ = new Asn1UTF8String("Homeland Security Advisory System Update");
            
            alert.info_list[0].urgency = new Alert_info_urgency(Alert_info_urgency.immediate);
            
            alert.info_list[0].severity = new Alert_info_severity(Alert_info_severity.severe);
            
            alert.info_list[0].certainty = new Alert_info_certainty(Alert_info_certainty.likely);
            
            alert.info_list[0].senderName = new Asn1UTF8String("U.S. Government, Department of Homeland Security");
            
            alert.info_list[0].headline = new Asn1UTF8String("Homeland Security Sets Code ORANGE");
            
            alert.info_list[0].description = new Asn1UTF8String("The Department of Homeland Security has elevated the Homeland Security Advisory System threat level to ORANGE / High in response to intelligence which may indicate a heightened threat of terrorism.");
            
            alert.info_list[0].instruction = new Asn1UTF8String(" A High Condition is declared when there is a high risk of terrorist attacks. In addition to the Protective Measures taken in the previous Threat Conditions, Federal departments and agencies should consider agency specific Protective Measures in accordance with their existing plans.");
            
            alert.info_list[0].web = new Asn1UTF8String("http://www.dhs.gov/dhspublic/display?theme=29");
            
            alert.info_list[0].parameter_list = new Asn1UTF8String[1];
            alert.info_list[0].parameter_list[0] = new Asn1UTF8String("HSAS=ORANGE");
            
            alert.info_list[0].resource_list = new Alert_info_resource[1];
            alert.info_list[0].resource_list[0] = new Alert_info_resource();
            alert.info_list[0].resource_list[0].resourceDesc = new Asn1UTF8String("Image file (GIF)");
            
            alert.info_list[0].resource_list[0].uri = new Asn1UTF8String("http://www.dhs.gov/dhspublic/getAdvisoryImage");
            
            alert.info_list[0].area_list = new Alert_info_area[1];
            alert.info_list[0].area_list[0] = new Alert_info_area();
            alert.info_list[0].area_list[0].areaDesc = new Asn1UTF8String("U.S. nationwide and interests worldwide");
            
            alert.Encode(encodeBuffer);
            if (trace)
            {
               System.Console.Out.WriteLine("Encoding was successful");
               encodeBuffer.Write(System.Console.OpenStandardOutput());
            }
            
            // Write the encoded record to a file
            
            encodeBuffer.Write(new System.IO.FileStream(filename, System.IO.FileMode.Create));
         }
         catch (System.Exception e)
         {
            System.Console.Out.WriteLine(e.Message);
            Asn1Util.WriteStackTrace(e, Console.Error);
            return ;
         }
      }
   }
}