// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.10, Date: 01-Jul-2008.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace Microsoft.Protocols.TestTools.StackSdk.Security.Kile {

   public class AD_IF_RELEVANT : AuthorizationData {
      public AD_IF_RELEVANT () : base()
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      public AD_IF_RELEVANT (int numRecords) : base (numRecords)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      public AD_IF_RELEVANT (AuthorizationData_element[] elements_) :
         base (elements_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

   }
}
