// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.10, Date: 01-Jul-2008.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace Microsoft.Protocols.TestTools.StackSdk.Security.Kile {

   public class Authenticator : Asn1Type {
      public new readonly static Asn1Tag _TAG = new Asn1Tag (Asn1Tag.APPL, Asn1Tag.CONS, 2);

      public Asn1Integer authenticator_vno;
      public Realm crealm;
      public PrincipalName cname;
      public Checksum cksum;  // optional
      public Microseconds cusec;
      public KerberosTime ctime;
      public EncryptionKey subkey;  // optional
      public UInt32 seq_number;  // optional
      public AuthorizationData authorization_data;  // optional

      public Authenticator () : base()
      {
         Init();
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor sets all elements to references to the 
      /// given objects
      /// </summary>
      public Authenticator (
         Asn1Integer authenticator_vno_,
         Realm crealm_,
         PrincipalName cname_,
         Checksum cksum_,
         Microseconds cusec_,
         KerberosTime ctime_,
         EncryptionKey subkey_,
         UInt32 seq_number_,
         AuthorizationData authorization_data_
      )
         : base ()
      {
         authenticator_vno = authenticator_vno_;
         crealm = crealm_;
         cname = cname_;
         cksum = cksum_;
         cusec = cusec_;
         ctime = ctime_;
         subkey = subkey_;
         seq_number = seq_number_;
         authorization_data = authorization_data_;
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor is for required elements only.  It sets 
      /// all elements to references to the given objects
      /// </summary>
      public Authenticator (
         Asn1Integer authenticator_vno_,
         Realm crealm_,
         PrincipalName cname_,
         Microseconds cusec_,
         KerberosTime ctime_
      )
         : base ()
      {
         authenticator_vno = authenticator_vno_;
         crealm = crealm_;
         cname = cname_;
         cusec = cusec_;
         ctime = ctime_;
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor allows primitive data to be passed for all 
      /// primitive elements.  It will create new object wrappers for 
      /// the primitive data and set other elements to references to 
      /// the given objects 
      /// </summary>
      public Authenticator (long authenticator_vno_,
         string crealm_,
         PrincipalName cname_,
         Checksum cksum_,
         long cusec_,
         string ctime_,
         EncryptionKey subkey_,
         long seq_number_,
         AuthorizationData authorization_data_
      )
         : base ()
      {
         authenticator_vno = new Asn1Integer (authenticator_vno_);
         crealm = new Realm (crealm_);
         cname = cname_;
         cksum = cksum_;
         cusec = new Microseconds (cusec_);
         ctime = new KerberosTime (ctime_);
         subkey = subkey_;
         seq_number = new UInt32 (seq_number_);
         authorization_data = authorization_data_;
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor is for required elements only.  It allows 
      /// primitive data to be passed for all primitive elements.  
      /// It will create new object wrappers for the primitive data 
      /// and set other elements to references to the given objects. 
      /// </summary>
      public Authenticator (
         long authenticator_vno_,
         string crealm_,
         PrincipalName cname_,
         long cusec_,
         string ctime_
      )
         : base ()
      {
         authenticator_vno = new Asn1Integer (authenticator_vno_);
         crealm = new Realm (crealm_);
         cname = cname_;
         cusec = new Microseconds (cusec_);
         ctime = new KerberosTime (ctime_);
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      public void Init () {
         authenticator_vno = null;
         crealm = null;
         cname = null;
         cksum = null;
         cusec = null;
         ctime = null;
         subkey = null;
         seq_number = null;
         authorization_data = null;
      }

      public override void Decode
         (Asn1BerDecodeBuffer buffer, bool explicitTagging, int implicitLength)
      {
         int llen = (explicitTagging) ?
            MatchTag (buffer, _TAG) : implicitLength;

         int llen2 = llen;
         llen = MatchTag (buffer, Asn1Tag.SEQUENCE);

         Init ();

         // decode SEQUENCE

         Asn1BerDecodeContext _context =
            new Asn1BerDecodeContext (buffer, llen);

         IntHolder elemLen = new IntHolder();

         // decode authenticator_vno

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 0, elemLen, true)) {
            authenticator_vno = new Asn1Integer();
            authenticator_vno.Decode (buffer, true, elemLen.mValue);
            if (!(authenticator_vno.mValue == 5)) {
               throw new Asn1ConsVioException ("authenticator_vno.mValue", authenticator_vno.mValue);
            }

            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode crealm

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 1, elemLen, true)) {
            crealm = new Realm();
            crealm.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode cname

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 2, elemLen, true)) {
            cname = new PrincipalName();
            cname.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode cksum

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 3, elemLen, true)) {
            cksum = new Checksum();
            cksum.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }

         // decode cusec

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 4, elemLen, true)) {
            cusec = new Microseconds();
            cusec.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode ctime

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 5, elemLen, true)) {
            ctime = new KerberosTime();
            ctime.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode subkey

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 6, elemLen, true)) {
            subkey = new EncryptionKey();
            subkey.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }

         // decode seq_number

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 7, elemLen, true)) {
            seq_number = new UInt32();
            seq_number.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }

         // decode authorization_data

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 8, elemLen, true)) {
            authorization_data = new AuthorizationData();
            authorization_data.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }

         if (llen == Asn1Status.INDEFLEN) {
            MatchTag (buffer, Asn1Tag.EOC);
         }
         if (explicitTagging && llen2 == Asn1Status.INDEFLEN) {
            MatchTag (buffer, Asn1Tag.EOC);
         }
      }

      public override int Encode (Asn1BerEncodeBuffer buffer, bool explicitTagging)
      {
         int _aal = 0, len;

         // encode authorization_data

         if (authorization_data != null) {
            len = authorization_data.Encode (buffer, true);
            _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 8, len);
            _aal += len;
         }

         // encode seq_number

         if (seq_number != null) {
            len = seq_number.Encode (buffer, true);
            _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 7, len);
            _aal += len;
         }

         // encode subkey

         if (subkey != null) {
            len = subkey.Encode (buffer, true);
            _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 6, len);
            _aal += len;
         }

         // encode ctime

         len = ctime.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 5, len);
         _aal += len;

         // encode cusec

         len = cusec.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 4, len);
         _aal += len;

         // encode cksum

         if (cksum != null) {
            len = cksum.Encode (buffer, true);
            _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 3, len);
            _aal += len;
         }

         // encode cname

         len = cname.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 2, len);
         _aal += len;

         // encode crealm

         len = crealm.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 1, len);
         _aal += len;

         // encode authenticator_vno

         if (!(authenticator_vno.mValue == 5)) {
            throw new Asn1ConsVioException ("authenticator_vno.mValue", authenticator_vno.mValue);
         }

         len = authenticator_vno.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 0, len);
         _aal += len;

         _aal += buffer.EncodeTagAndLength (Asn1Tag.SEQUENCE, _aal);

         if (explicitTagging) {
            _aal += buffer.EncodeTagAndLength (_TAG, _aal);
         }

         return (_aal);
      }

   }
}
