// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.10, Date: 01-Jul-2008.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace Microsoft.Protocols.TestTools.StackSdk.Security.Kile {

   public class KDC_REP : Asn1Type {
      public Asn1Integer pvno;
      public Asn1Integer msg_type;
      public _SeqOfPA_DATA padata;  // optional
      public Realm crealm;
      public PrincipalName cname;
      public Ticket ticket;
      public EncryptedData enc_part;

      public KDC_REP () : base()
      {
         Init();
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor sets all elements to references to the 
      /// given objects
      /// </summary>
      public KDC_REP (
         Asn1Integer pvno_,
         Asn1Integer msg_type_,
         _SeqOfPA_DATA padata_,
         Realm crealm_,
         PrincipalName cname_,
         Ticket ticket_,
         EncryptedData enc_part_
      )
         : base ()
      {
         pvno = pvno_;
         msg_type = msg_type_;
         padata = padata_;
         crealm = crealm_;
         cname = cname_;
         ticket = ticket_;
         enc_part = enc_part_;
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor is for required elements only.  It sets 
      /// all elements to references to the given objects
      /// </summary>
      public KDC_REP (
         Asn1Integer pvno_,
         Asn1Integer msg_type_,
         Realm crealm_,
         PrincipalName cname_,
         Ticket ticket_,
         EncryptedData enc_part_
      )
         : base ()
      {
         pvno = pvno_;
         msg_type = msg_type_;
         crealm = crealm_;
         cname = cname_;
         ticket = ticket_;
         enc_part = enc_part_;
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor allows primitive data to be passed for all 
      /// primitive elements.  It will create new object wrappers for 
      /// the primitive data and set other elements to references to 
      /// the given objects 
      /// </summary>
      public KDC_REP (long pvno_,
         long msg_type_,
         _SeqOfPA_DATA padata_,
         string crealm_,
         PrincipalName cname_,
         Ticket ticket_,
         EncryptedData enc_part_
      )
         : base ()
      {
         pvno = new Asn1Integer (pvno_);
         msg_type = new Asn1Integer (msg_type_);
         padata = padata_;
         crealm = new Realm (crealm_);
         cname = cname_;
         ticket = ticket_;
         enc_part = enc_part_;
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor is for required elements only.  It allows 
      /// primitive data to be passed for all primitive elements.  
      /// It will create new object wrappers for the primitive data 
      /// and set other elements to references to the given objects. 
      /// </summary>
      public KDC_REP (
         long pvno_,
         long msg_type_,
         string crealm_,
         PrincipalName cname_,
         Ticket ticket_,
         EncryptedData enc_part_
      )
         : base ()
      {
         pvno = new Asn1Integer (pvno_);
         msg_type = new Asn1Integer (msg_type_);
         crealm = new Realm (crealm_);
         cname = cname_;
         ticket = ticket_;
         enc_part = enc_part_;
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      public void Init () {
         pvno = null;
         msg_type = null;
         padata = null;
         crealm = null;
         cname = null;
         ticket = null;
         enc_part = null;
      }

      public override void Decode
         (Asn1BerDecodeBuffer buffer, bool explicitTagging, int implicitLength)
      {
         int llen = (explicitTagging) ?
            MatchTag (buffer, Asn1Tag.SEQUENCE) : implicitLength;

         Init ();

         // decode SEQUENCE

         Asn1BerDecodeContext _context =
            new Asn1BerDecodeContext (buffer, llen);

         IntHolder elemLen = new IntHolder();

         // decode pvno

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 0, elemLen, true)) {
            pvno = new Asn1Integer();
            pvno.Decode (buffer, true, elemLen.mValue);
            if (!(pvno.mValue == 5)) {
               throw new Asn1ConsVioException ("pvno.mValue", pvno.mValue);
            }

            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode msg_type

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 1, elemLen, true)) {
            msg_type = new Asn1Integer();
            msg_type.Decode (buffer, true, elemLen.mValue);
            if (!((msg_type.mValue == 11 || msg_type.mValue == 13))) {
               throw new Asn1ConsVioException ("msg_type.mValue", msg_type.mValue);
            }

            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode padata

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 2, elemLen, true)) {
            padata = new _SeqOfPA_DATA();
            padata.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }

         // decode crealm

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 3, elemLen, true)) {
            crealm = new Realm();
            crealm.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode cname

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 4, elemLen, true)) {
            cname = new PrincipalName();
            cname.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode ticket

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 5, elemLen, true)) {
            ticket = new Ticket();
            ticket.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         // decode enc_part

         if (_context.MatchElemTag (Asn1Tag.CTXT, Asn1Tag.CONS, 6, elemLen, true)) {
            enc_part = new EncryptedData();
            enc_part.Decode (buffer, true, elemLen.mValue);
            if (elemLen.mValue == Asn1Status.INDEFLEN) {
               MatchTag (buffer, Asn1Tag.EOC);
            }
         }
         else throw new Asn1MissingRequiredException (buffer);

         if (explicitTagging && llen == Asn1Status.INDEFLEN) {
            MatchTag (buffer, Asn1Tag.EOC);
         }
      }

      public override int Encode (Asn1BerEncodeBuffer buffer, bool explicitTagging)
      {
         int _aal = 0, len;

         // encode enc_part

         len = enc_part.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 6, len);
         _aal += len;

         // encode ticket

         len = ticket.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 5, len);
         _aal += len;

         // encode cname

         len = cname.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 4, len);
         _aal += len;

         // encode crealm

         len = crealm.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 3, len);
         _aal += len;

         // encode padata

         if (padata != null) {
            len = padata.Encode (buffer, true);
            _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 2, len);
            _aal += len;
         }

         // encode msg_type

         if (!((msg_type.mValue == 11 || msg_type.mValue == 13))) {
            throw new Asn1ConsVioException ("msg_type.mValue", msg_type.mValue);
         }

         len = msg_type.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 1, len);
         _aal += len;

         // encode pvno

         if (!(pvno.mValue == 5)) {
            throw new Asn1ConsVioException ("pvno.mValue", pvno.mValue);
         }

         len = pvno.Encode (buffer, true);
         _aal += buffer.EncodeTagAndLength (Asn1Tag.CTXT, Asn1Tag.CONS, 0, len);
         _aal += len;

         if (explicitTagging) {
            _aal += buffer.EncodeTagAndLength (Asn1Tag.SEQUENCE, _aal);
         }

         return (_aal);
      }

   }
}
