// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.10, Date: 01-Jul-2008.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace Microsoft.Protocols.TestTools.StackSdk.Security.Kile {

   public class KerberosString : Asn1GeneralString {
      public KerberosString () : base()
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      public KerberosString (string value_) : base (value_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

   }
}
