// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.10, Date: 01-Jul-2008.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace Microsoft.Protocols.TestTools.StackSdk.Security.Kile {

   public class KerberosTime : Asn1GeneralizedTime {
      public KerberosTime () : base (false)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }
      public KerberosTime (bool useDER) :
         base (useDER)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      public KerberosTime (string value) :
         base (value)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      public KerberosTime (string value, bool useDER) :
         base (value, useDER)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

   }
}
