// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.10, Date: 01-Jul-2008.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace Microsoft.Protocols.TestTools.StackSdk.Security.Kile {

   public class PA_ENC_TIMESTAMP : EncryptedData {
      public PA_ENC_TIMESTAMP () : base()
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor sets all elements to references to the 
      /// given objects
      /// </summary>
      public PA_ENC_TIMESTAMP (
         Int32 etype_,
         UInt32 kvno_,
         Asn1OctetString cipher_
      )
         : base (etype_, kvno_, cipher_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor is for required elements only.  It sets 
      /// all elements to references to the given objects
      /// </summary>
      public PA_ENC_TIMESTAMP (
         Int32 etype_,
         Asn1OctetString cipher_
      )
         : base (etype_, cipher_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor allows primitive data to be passed for all 
      /// primitive elements.  It will create new object wrappers for 
      /// the primitive data and set other elements to references to 
      /// the given objects 
      /// </summary>
      public PA_ENC_TIMESTAMP (long etype_,
         long kvno_,
         byte[] cipher_
      )
         : base (etype_, kvno_, cipher_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor is for required elements only.  It allows 
      /// primitive data to be passed for all primitive elements.  
      /// It will create new object wrappers for the primitive data 
      /// and set other elements to references to the given objects. 
      /// </summary>
      public PA_ENC_TIMESTAMP (
         long etype_,
         byte[] cipher_
      )
         : base (etype_, cipher_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

   }
}
