// 
// This file was generated by the Objective Systems ASN1C Compiler
// (http://www.obj-sys.com).  Version: 6.10, Date: 01-Jul-2008.
// 
using System;
using Com.Objsys.Asn1.Runtime;

namespace Microsoft.Protocols.TestTools.StackSdk.Security.Kile {

   public class TGS_REP : KDC_REP {
      public new readonly static Asn1Tag _TAG = new Asn1Tag (Asn1Tag.APPL, Asn1Tag.CONS, 13);

      public TGS_REP () : base()
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor sets all elements to references to the 
      /// given objects
      /// </summary>
      public TGS_REP (
         Asn1Integer pvno_,
         Asn1Integer msg_type_,
         _SeqOfPA_DATA padata_,
         Realm crealm_,
         PrincipalName cname_,
         Ticket ticket_,
         EncryptedData enc_part_
      )
         : base (pvno_, msg_type_, padata_, crealm_, cname_, ticket_, enc_part_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor is for required elements only.  It sets 
      /// all elements to references to the given objects
      /// </summary>
      public TGS_REP (
         Asn1Integer pvno_,
         Asn1Integer msg_type_,
         Realm crealm_,
         PrincipalName cname_,
         Ticket ticket_,
         EncryptedData enc_part_
      )
         : base (pvno_, msg_type_, crealm_, cname_, ticket_, enc_part_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor allows primitive data to be passed for all 
      /// primitive elements.  It will create new object wrappers for 
      /// the primitive data and set other elements to references to 
      /// the given objects 
      /// </summary>
      public TGS_REP (long pvno_,
         long msg_type_,
         _SeqOfPA_DATA padata_,
         string crealm_,
         PrincipalName cname_,
         Ticket ticket_,
         EncryptedData enc_part_
      )
         : base (pvno_, msg_type_, padata_, crealm_, cname_, ticket_, enc_part_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      /// <summary>
      /// This constructor is for required elements only.  It allows 
      /// primitive data to be passed for all primitive elements.  
      /// It will create new object wrappers for the primitive data 
      /// and set other elements to references to the given objects. 
      /// </summary>
      public TGS_REP (
         long pvno_,
         long msg_type_,
         string crealm_,
         PrincipalName cname_,
         Ticket ticket_,
         EncryptedData enc_part_
      )
         : base (pvno_, msg_type_, crealm_, cname_, ticket_, enc_part_)
      {
         SetKey (_KerberosV5Spec2Values._rtkey);
      }

      public override void Decode
         (Asn1BerDecodeBuffer buffer, bool explicitTagging, int implicitLength)
      {
         int llen = implicitLength;

         if (explicitTagging) {
            llen = MatchTag (buffer, _TAG);
         }

         base.Decode (buffer, true, llen);

         if (explicitTagging && llen == Asn1Status.INDEFLEN) {
            MatchTag (buffer, Asn1Tag.EOC);
         }

      }

      public override int Encode (Asn1BerEncodeBuffer buffer, bool explicitTagging)
      {
         int _aal = base.Encode (buffer, true);

         if (explicitTagging) {
            _aal += buffer.EncodeTagAndLength (_TAG, _aal);
         }

         return (_aal);
      }

   }
}
